### PR TITLE
Create item_mods2.sql

### PR DESCRIPTION
**Pull request by bn7**
Will this work? you can even put them in the normal item mods. This will allow for more gear and less having to deal with git hub

### CODE REVIEW

**Comment by Ninjistix** [comment]
No this wil not work.. the sql isn't coded into core so this file is useless

**Comment by bn7** [comment]
not for you to be able to cut and past in to the normal. This is just terminal gear

**Comment by Ninjistix** [comment]
you can edit the item mods sql and submit that normally with the changes, of less than 100 lines... also this sql deletes the previous item mod table.. which would delete all other mods except these

**Comment by bn7** [comment]
No Github, DS , and  tortoise hate me that is why I was trying another way

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Ninjistix** [comment]
There's a guide on the forum on how to setup and use tortoise it's only the
basics I'd say commit everything to a new branch and amend updates

**Pull request closed without merging**
