### PR TITLE
Create fire_vi.lua

### PR DESCRIPTION
**Pull request by bn7**

### CODE REVIEW

**Comment by Ninjistix** [comment]
are these assumed stats?

**Comment by bn7** [comment]
I do not even think that DS is correct with the I-V spells

http://ffxiclopedia.wikia.com/wiki/Calculating_Magic_Damage

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Ninjistix** [comment]
yeah but that page has no info for the V+ spells

**Comment by bn7** [comment]
see My 2nd link

https://github.com/Windower/Resources/blob/master/lua/spells.lua
level=

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request merged**
